#+TITLE:Camp
#+AUTHOR:Crinkly Friend

* Good Morning, Adventure!
Oshawott awoke with a start. This tiny otter wasn't a morning Pokemon in the slightest, but there were no signs of drowsiness across his white freckled face as the straw bed he was sleeping on scattered slightly across the dirt floor. He might have been dreaming a few moments ago, but couldn't remember what it was because his subconscious had just roused him with something very, very important.

It was finally time! Oshawott could barely contain his excitement that the camping trip him and his friends had been planning for the last several months was finally here!

The brisk morning air wafted through the door of the house and chilled the now-exposed belly Oshawott was sleeping on. He shivered slightly as he picked the scalchop off the ground next to him and placed it where it belonged on his belly, tucking it slightly into the white, crinkly undergarment he was sleeping in. Oshawott inspected the diaper around his waist and frowned slightly as he noticed that the pattern on the front of it was faded slightly. He didn't quite make it through the night this time. He wasn't going to let that get him too down though, today was going to be so much fun!

Oshawott pulled down the diaper, rolled it up, and placed it in a bag in the corner of the single wooded room that his house consisted of, making a mental note to replace it upon seeing that it was nearly full. After sealing the bag again, he inspected the wall above the bag, where a calendar sat pinned, many of the days crossed out. Oshawott sighed, and grabbed the piece of charcoal hanging next to the calendar to cross off another day.

Oshawott tilted his head down to examine his lap. After inspecting it thoughtfully for a moment, he inhaled deeply so his chest swelled, and moments later unleashed a jet of water to clean himself up.

As ashamed he would be to admit it, Oshawott was actually quite used to this morning routine. But that wasn't important to him right now, this momentary reduction of momentum was complete, and he was going to have the best day ever!

It had been a long time since Oshawott had seen his friends Snivy and Emolga, but they were finally going to be right here in Post Town with him! In a few short hours, he was going to be reunited with his best friends, and they were going to go on an excursion unlike any they had been on before!

Emolga had discovered a beautiful river they were planning on making their destination--one where the moonlight refracted on the surrounding crystalline cliffs every night to make a beautiful purple lightshow shimmer on the surface of the water. Oshawott's eyes sparkled at the thought of a place so beautiful to camp with his friends. They were going to stay up all night, and make a fire, and roast berries, and tell scary stories, and, and...

Oshawott beamed at the ceiling with an ecstatic expression. They were going to finally be together again!

With the extra energy he felt from these pleasant mental images, he bolted out the door. Oshawott wasn't in a hurry, but he couldn't help it.

* The Whirlwind
When Oshawott arrived at the main square of Post Town, he was absolutely exhausted. There weren't many Pokemon here this early in the morning, and the ones who were seemed to take no notice of the panting Pokemon who had just arrived. The place he was going to meet with his two companions was just up a set of wooden stairs from this plaza, but Oshawott knew they wouldn't be there yet. He became slightly irritated with himself for waking up so early, since the next few hours were undoubtedly going to last forever.

Oshawott considered what he could do to pass the time, but none of the shops were open yet, and he wasn't going to meet his friends for another four hours! He wracked his mind for a solution that didn't involve running around in circles until he wore a hole in the ground. Maybe he should check the meeting place? There wasn't going to be anyone there, but it was *something* to do, and maybe it would prove a more comfortable setting for his current mulling. This seemed like a good enough reason to him, so Oshawott strode towards the stairway, which looked a little more welcoming now.

Watching his feet as he walked, Oshawott ascended the stairway onto the top of the hill. Then, surveying the plaza in front of him and the forest beyond, Oshawott decided that he made the right choice to come here. It was very beautiful this early in the morning, and the soothing environment calmed his emotions. He was still anxious to meet his friends, but the time before they would be there seemed just a tiny bit more bearable now.

Oshawott sat down next to a fountain in the middle of the plaza and gazed out at the rising sun shimmering over the treetops. The running water reminded him of the dream he was sure he forgot in the morning's excitement. A sense that the fog in his memory of it was slowly ebbing, Oshawott sat there for a few minutes with a bemused expression on his face. What had he been dreaming? Did he remember anything more than the sounds of water?

Try as he might, Oshawott couldn't remember anything else! His dreams weren't a significant part of his day, but the thought that his mind was dangling a story he had experienced just out of reach of his stream of consciousness was slightly frustrating. Besides, it's not like he had anything else to do right now. So he sat, anchored to the ground, straining his mind to recall. What was the last thing he remembered?

The morning silence, and the serene air of the plaza was perfect for concentration, but even with the benefit of the environment on his side, the images remained elusive; their evanescence triumphing over Oshawott's efforts to evoke them from the depths of his memory.

Oshawott frowned. This wouldn't do. He had to stop thinking about it or he was going to go crazy, but thinking about nothing would make him go crazy too.

"HEY!"

A voice screamed out behind Oshawott, abruptly shattering the silence and causing him to jolt out of his contemplative state into sheer panic. Oshawott swung around and nearly collided with the source of the havoc, who was grinning fiendishly at him.

"E-Emolga! I nearly had a heart attack!" Oshawott wheezed at the flying squirrel who was now chortling at his reaction. He would have been mad at him, but he was so happy to see his friend again that he settled for relief instead. The wait was over!

"What are you doing here so early??" Oshawott questioned, still flabbergasted. Emolga continued giggling, undoubtedly with the mental image of Oshawott's expression a few moments earlier etched in his mind. The giggling became subdued for a moment, but as Emolga tried to hold it in, tears started welling up in the corner of his eyes as he began anew. It looked like he was about to keel over.

"I'm sorry" Emolga managed to slip out between a few short giggles that were now contagiously sneaking their way over to Oshawott's face. "I couldn't sleep, so I made the trip a little early! I didn't expect to see you here though." Emolga continued, his giggles finally relaxing into a warm smile, barely concealing the excitement underneath. Oshawott couldn't help but feel happy at all the positive energy radiating from his friend who had nearly knocked him into the fountain with the power of his own reflexes a moment earlier.

"Whaddaya say we pick up the last things we'll need for our trip?" Emolga suggested, glancing at the wooden staircase to the main square of Post Town. "The shops in the square should be opening any minute now!" Emolga continued, closing his eyes and grinning. That sounded a lot more exciting to Oshawott than just sitting around. "Y-yeah!" he replied, still taken aback by the juxtaposition of how chaotic everything had suddenly become. "Then let's gooo!!" Emolga exclaimed, already striding to the stairs. "Hey! Wait!" Oshawott called out as he stood up to follow the energetic rodent, but his friend was already descending to the square below.

As Oshawott hurried to the stairs in pursuit of the animate thunderbolt he called Emolga, he caught one last glimpse of the fountain where he was sitting and noticed the puddle on the ground where he once was. His heart sunk a little. "It must have been the fountain" he reasoned as he continued his descent, entering the square of Post Town where Emolga was standing, waiting for his descent.

"Jeez. Tookya long enough!" Emolga smiled in a way that showed that he wasn't actually disappointed. "If we're gonna be trekking out, we'll need some berries and maybe a bag to carry everything in!". Oshawott already had a bag, since adventuring was what he did as a living. That meant that he only needed to get enough food and water to last the trip.

The two of them scurried from shop to shop, exchanging stories about what they had been doing since they last met. Emolga told Oshawott about how he had finally managed to get himself a house like Oshawott's, so he was living on his own now. But it sounded like this existence wasn't nearly chaotic enough for Emolga, who much preferred the company of his 3 roommates where he used to live. Oshawott enjoyed company too, of course. But he was actually really happy on his own, and was grateful for the freedom it allowed him. Plus he had a secret that he absolutely couldn't let leave his walls, so having a roommate would probably prove difficult in his case.

The remaining time before Snivy was supposed to arrive flew by like Emolga did whenever he saw an exceptionally high cliff he wanted to glide from.

"Oh! Snivy should be here soon, but she's not used to this part of town." Emolga explained. Oshawott nodded his head in acknowledgment. He of course knew this, but he was grateful that Emolga seemed cognizant of this fact as well. He had thought that Emolga and Snivy were going to arrive at the meeting place together, and had started wondering how they were going to meet up since it seemed like Snivy's guide had gotten here four hours earlier without her.

Emolga considered the thoughtful expression that Oshawott must have been wearing and continued "I'm gonna go get her at the edge of town! You should pack your new stuff in the meantime!" Oshawott nodded with a quizzical look on his face "Okay! I'll see you back here in...how long do you think?" Emolga giggled at the question and with a warm expression replied "Does it matter? Let's all just get back together as fast as we can!". Oshawott had no complaints with this line of reasoning. He just needed to get back to his house and pack a few things for his trip, and they could finally begin their adventure!

As Emolga turned to seek out their final party member, something occurred to Oshawott. "How long do you think we'll be out?" he asked. Emolga peeked over his shoulder at Oshawott and with a sparkle in his eye, answered "Oh! At least three days!" and before Oshawott could respond, zoomed off in search of Snivy.

Oshawott stood there for a moment, excited that he was about to spend so much quality time with his friends. He had never been on a trip that lasted more than a day. He considered this for a moment before his heart sunk at the realization. "Wait, THREE DAYS??" Oshawott bellowed at Emolga, but he was already out of earshot, and there was no way Oshawott could catch up now.

Oshawott had planned to stay up all night and play games during the trip, but if they were going to be out for three whole days, there's no way he could stay up that long! And if he was going to need to sleep, he also needed *those*.

Oshawott needed to bring his diapers, and he needed to keep them a secret.

* Emotional Baggage
The walk back home was torment for Oshawott. What was he going to do? He couldn't just *not* go, but if he went, his friends would discover his bedwetting problem for sure! Who wears diapers at his age? He held a job, had a house, but this facade of maturity would all fall if he was discovered.

Maybe he could just risk it, and ignore the puddles he might leave? After all, this was the wilderness, and it's not like that would be a problem. But no! Emolga was bringing beds, and it would look really strange to offer to sleep on the hard ground. Besides, Oshawott shuddered, he couldn't do that. It would probably be impossible to sleep on the cold, hard ground.

Oshawott strode quickly out of town towards his house, hoping desperately to buy himself a little extra time to formulate a plan. Emolga and Snivy were going to be disgusted with him, he just knew it! This trip was bound to be a disaster if he didn't think about something quickly! Oshawott pace quickened to a sprint, leaving small dust clouds with each footfall.

Oshawott was sweating once again by the time he reached his house, but this time it wasn't because of his sustained pace. Oshawott strode into his house with purpose, snatched his bag from the wall, and started stuffing the supplies Emolga and he had picked up from Post Town, his eyes darting around his house for some clue about what he could use to keep his secret without looking too suspicious.

His eyes settled on a cloth he would sometimes use to dry himself. That was it! That was the answer Oshawott was looking for! His heart raced as he pulled it down and stuffed it in his bag. He would simply sleep under this! And if either of them asked, he would simply say that he gets cold at night! Oshawott's heart was still thumping as if it were ready to jump out of his chest entirely, but he had a plan! This trip was still salvageable, he just needed to be *very* careful.

The last thing Oshawott needed to put into his bag were his diapers. He was grateful for being a water type, because it meant he didn't need any other changing supplies.

Oshawott fetched a few diapers that were neatly stacked under a worn-looking cloth from the far side of the room and carried them over to his bag. He could wrap these in the cloth he packed earlier so that nobody would see them when he opened his bag too! Oshawott flung the bag open hurriedly and extracted the cloth from earlier, and started to wrap the diapers in them.

"Oshawott!!" a voice called out outside. Oshawott's heart skipped a beat; that sounded like, Emolga?? What was he doing here already? Wasn't he supposed to be getting Snivy?! There's no way that the two of them had already met up. After all, *he* had just gotten here, and he had done so in a hurry.

"Did you get Snivy?" Oshawott responded in a voice that shook slightly. He wasn't sure if Emolga noticed, but he certainly did. Was there a problem? Did Emolga forget about Snivy?? Either way, this question seemed like the best bet for getting Emolga to leave as quickly as possible without any questions.

Oshawott's plan evidently hadn't worked, because he saw Emolga's shadow by the door. Oh no no no no no! This couldn't be happening!

Emolga's shadow had a strange gait to it, he was walking strangely for some reason. Oshawott would have wondered why if he wasn't still wrestling with the fact he was here to begin with. Emolga inched into Oshawott's house backwards, which struck Oshawott as both odd and surprisingly considerate given how he had expected Emolga to essentially sprint in. That was, until he realized that Emolga was in this curious position because he had someone in tow, and that "someone" was Snivy!

"She was on her way to your house!" Emolga declared excitedly, looking over his shoulder as best as he could from his position at Oshawott's flustered face. The three Pokemon now stood in Oshawott's house.

"I'm sorry Oshawott." Snivy sighed coolly. "I didn't want to just barge in, but it looks like this dork really couldn't wait to get us all together." Snivy continued as she shook her head with a slight smile on her face. Oshawott had just finished wrapping the diapers in the cloth, so they were currently hidden, but he hadn't managed to put them in his bag yet. "This is bad!" Oshawott thought to himself. Snivy's sure to know something's up!

And sure enough, Snivy's smile vanished when she noticed the mortified expression that Oshawott was trying so hard to hide. Her expression intensified as she briefly swept the room with her gaze. Oshawott started to shiver. What was he going to do now? The jig was up. Snivy knew something was wrong, and any second now, Snivy was going to blow his secret wide open.

Snivy closed her eyes and opened her mouth to speak as Oshawott braced himself for what was about to follow. Then she spoke softly "Maybe we should go to Post Town and not distract Oshawott while he's packing."

Snivy made eye contact with Oshawott, who's shivering stopped upon hearing these words. He couldn't believe it. His gratitude for Snivy was boundless. She must have noticed this change of demeanor because a slight smirk crossed her face as she continued "That way we can start our trip as soon as possible." Emolga's eyes lit up "Yeah! Let's go finish up now that we've all seen each other!"

Snivy shot a knowing look at Oshawott, d-did she know? Or was she only working off his despaired expression? Oshawott was sure it was the latter, but he could never be 100% sure with Snivy. She was extremely clever in ways that absolutely bewildered him, and it always seemed like she knew more than she ever let on. But no! There's no way she knew, because she was still standing here with Emolga. They would have both left if they ever learned his secret, Oshawott was sure of it. He felt guilty for misleading them.

The two of them left the house, Emolga significantly ahead of the calm and collected Snivy. Oshawott packed the wrapped diapers into his bag and followed, this was the last thing that he needed to bring. "Actually, I'm done!" Oshawott called out as he followed. Snivy nodded in approval as the three of them had all now left the house. "He sure can get ahead of himself, huh?" she murmured, gesturing at the black blur that was their friend in the distance. Oshawott nodded in response distractedly.

Oshawott's mind was still racing. That could have been really, *really* bad, but things seemed to have worked out in the end. Plus he had a plan! His hope that everything was going to be every bit as good as he had hoped sprung once again to life!

This positive thought was short-lived as a twinge of guilt crossed his mind. Oshawott felt guilty for misleading his friends. He knew as a fact that they would disown him if they ever learned his secret, so was it really right to hide it like this? This wasn't right.

Anxiety flooded his mind with the worst case scenarios he was now convinced weren't just fabrications of an anxious mind. He was not a good friend for this, what would happen if his secret got out?

As if the universe was listening to his thoughts, Oshawott stepped on the cloth he had hurriedly packed earlier while he was lost in thought. The corner now pinned to the ground, ripped the entire cloth out of his bag along with its contents. The force scattering his diapers everywhere along the pathway. It took a second for the gravity of the situation to sink in, his heart sinking into his stomach. Oh no!

Oh no! Oh no! Oh no no no nooooooo!

Oshawott felt sick. He had been imagining all kinds of terrible situations in his head so he could defend himself against them, but he had never imagined this! He glanced up, looking to see if Snivy had noticed, praying that by some miracle that she hadn't so he could clean this up and pack better! But to his horror, she was inspecting the diapery mess that was now surrounding her and Oshawott. Her lack of expression was so hard to read, was that disappointment, was it pity?!

"Oh." she said simply.

Maybe Emolga hadn't noticed?? Maybe he could clean up before he looked back and noticed the mess? Having at least one friend was good enough, wasn't it?! No, there was no way to fix this.

Oh gosh, he couldn't breathe. Oshawott couldn't breathe! What he wouldn't have given to travel back to what felt like an hour ago and just cancel the whole trip while everyone was in his house! But now he had no choice, he had to get out of here.

Oshawott sprinted, even faster than he did this morning to town. The day he was so convinced would be the best in the world had just turned into the worst in the universe. It was done, and he was done. His friends hated him, he had to get out of here, and he had to do it *now*.

He didn't have the energy to do any of that now though, so Oshawott resorted to the next best thing and collapsed into a sobbing heap. Maybe he would wake up from this nightmare and discover that he still had this day, and the meeting with his friends, /his precious friends/ to look forward to.

Oshawott was ruined.

* Leaving
Oshawott didn't know how much time had passed, but after he had calmed down a little, he steeled his resolve. He decided that this wasn't a great way to end a relationship with anyone. Even if his friends hated him, he had to apologize for misleading them. He needed to face the music, and then he had to leave. Images of Emolga holding him down while Snivy vine whipped his butt crossed his mind. He shuddered.

Oshawott was terrified, but he was determined that this was the right thing to do. He would do his best to steel himself and accept anything that they deemed he deserved, no matter what it was. He secretly hoped that whatever judgment awaited him would be harsh and painful. After all, he deserved it for deceiving his friends for so long, and for hurting them when they found out. Shaking, and with tears still in his eyes, Oshawott started walking back home. Would they even be there? He didn't know.

It didn't take long before he saw the outline of someone he recognized. It was Snivy, great. Her strength actually scared him a little, and there would be no escaping her if she got any closer. Oshawott winced. He guessed it was probably a good thing to get the worst retribution out of the way early.

Oshawott examined the outline in the distance, she was...sprinting? It was over, he couldn't outrun Snivy. He was at her mercy now. As she hastened closer to him, Oshawott could make out the extraordinarily unhappy expression plastered across her face. Whatever she was planning on dishing out, Oshawott intended to accept it, to be resolved. However Oshawott found his resolve wavering as the moment drew near, so he closed his eyes tightly. He was both ready and not ready for the pain to begin. Moments stretched into hours, until finally he felt something he had not expected at all. "W-wha..?" Oshawott gasped as he felt Snivy's warm embrace.

Oshawott looked down dumbfounded, Snivy was hugging him! She was hugging him *so* hard! But why?? Snivy saw what he was hiding, didn't she? Wasn't she mad? She should be mad! Oshawott *deserved* her wrath. "Don't you hate me for lying to you?" Oshawott whimpered, guilt flowing freely through his entire being. Snivy gazed up at Oshawott with a broken expression "Of course not, you idiot!" She squeezed him harder yet.

She... She didn't hate him. Against all odds, he still had Snivy, his dear friend. "My...friend" Oshawott repeated over and over in his mind. Oshawott hugged her back as his eyes blurred. Snivy wasn't much for emotions usually, but she made an exception this time for Oshawott, for her friend.

After they released each other, Oshawott rubbed his eyes and shakily began "Where's Emolga?". He almost didn't want to hear the answer--but he couldn't believe his luck that Snivy just happened to not hate him, and figured that if he wasn't lucky enough to keep *both* of his friends, he was in a better state to learn of it now.

Snivy turned her attention to the town in the distance "He was worried, so he ran after you."

Did...did he not hate Oshawott either? Though, now that he thought about it, Oshawott didn't recall seeing Emolga. He wasn't a Pokemon particularly known for his stealth, so where did he go? Was he still in Post Town? Did he see him collapse? "We..." Oshawott began "We need to find him." Snivy let go of Oshawott and nodded "Yeah. Knowing him, he's probably in the middle of the square making a scene."

Snivy's eyes were red, but she looked much happier now that Oshawott was back. How could anyone be happy with him after learning his secret? This thought swirled through Oshawott's psyche for a moment, was it really not as big of a deal as he thought it was? As the two Pokemon walked towards Post Town, Oshawott turned to his friend. "I'm sorry for doubting you" Oshawott began. "I was sure that you'd hate me when you learned about...about my problem."

Snivy's gaze grew intense at these words. She turned towards Oshawott and asked pointedly "Why would we do that? You're our friend you know!" her eyes narrowed "Do you really think something like this is enough to undo the friendship we have? That's not how relationships work! You're a big part of our lives, and removing yourself from them without hearing what we have to say is an awfully selfish thing to do!"

She was right, of course. Oshawott felt foolish, why had he doubted his friends? He still didn't know if they accepted his secret, but he knew that they certainly accepted *him*, and that was good enough for now.

As they arrived in Post Town, this train of though was abruptly cut off by a sight that Oshawott will never, *ever* forget. The two of them had found Emolga, yes; he was standing in the dead center of the town square. But around Emolga's waist was a diaper, and he looked absolutely livid.

Emolga started moving the second he noticed Oshawott and Snivy's approach, running swiftly towards them with a slight waddle. When close enough, Emolga slid to a stop and declared a little too loudly "See?? It's not a big deal!" Emolga's furious expression contorted to looking hurt "Do you really think that our friendship is hinged on you not being in diapers??"

Oshawott was flabbergasted, not only was he accepted by his friends, he was apparently worthy of this...unusual and extremely brave display to prove it. "What did Snivy think?" he wondered. There was no way that Snivy would be comfortable with such an over-the-top display. Oshawott peered at her. She was...smiling?

He was flustered and embarrassed, but most of all, Oshawott was sorry. He was sorry for doubting his friends, and he was sorry for letting something so minuscule grow to become such a dragon in his mind. How could he have been so wrong? Was he even worthy of all this kindness? He had been lousy, but his friends were there to support him, just like they always were. He hadn't let them down.

Despite the ridiculous situation he found himself in, for the first time since his secret was discovered, Oshawott's mouth slightly curved into a smile. Did he really mean this much to his friends? Emolga, who had been staring intensely at him with eyes that could pierce stone, softened at this reaction. After a brief moment of what looked like him processing what he just observed, Emolga's expression snapped to a proud smile. "Hehe, see?" he started "I toldja that it's not a big deal!" Emolga put his hands on his waist in a proud expression, which crinkled audibly. Just how did he do it? Oshawott marveled, how was Emolga so confident?

Emolga rummaged around his bag a little and fished out two pristine diapers. He tossed one to Snivy, and then the other to Oshawott, who fumbled it. Emolga smirked slyly "I'm gonna make sure you realize it too!" Oshawott couldn't believe it, did Emolga mean what he thought he meant? His mind shot in a thousand directions about what else this expression could possibly mean, but Oshawott's hesitation was interrupted by an impatient Emolga who noticed his dazed stupor. "Aren'cha gonna put it on?" he inquired. Oshawott couldn't believe his ears, was this really happening? They were in the middle of Post Town's busiest square! There's no way he could do this!

Oshawott glanced around nervously. There were many other Pokemon in the square, and while they obviously noticed the noisy rodent wearing a diaper in the middle of town, Oshawott comforted himself with the realization that they mostly kept going about their day. However, a few interested onlookers did occasionally eye Emolga curiously, one even staring for a few moments, obviously deep in thought. Oshawott didn't want to imagine what was going through their mind.

Speechless, Oshawott shot a glance at Snivy who he just now noticed was putting her diaper on. His jaw dropped, this was insane, how were they doing this?? Snivy noticed Oshawott's frozen expression, and eyed him expectantly. "Well?" she said with a smirk as she finished fastening her diaper without breaking eye contact.

Both of his friends were now wearing diapers in the middle of Post Town while Oshawott just stood paralyzed, clutching his diaper to his belly. Seeing his friends' courage on his behalf, Oshawott tried to psyche himself up. He *should* do this, he *could* do this. All of these years of him thinking that he was an outcast in training, those were going to end now! The fresh diaper felt cool between his arms, clean and pristine as fresh snow; a new beginning. Every muscle in Oshawott's body resisted doing what his friends had just bravely demonstrate to him was possible. But, he trusted them.

Slowly, he unfolded the diaper, the plastic felt softer than it ever had before. Oshawott pulled the diaper up between his feet and slowly, carefully aligned the front with the back, and fastened the two sides of the diaper with their respective tapes. He...he had done it! He was now standing in the middle of Post Town in a diaper, and nobody was throwing him out of town for it. But Oshawott was still painfully aware that he had caught some of Emolga's attention, there were Pokemon looking at him, he knew they were.

Even with his friends, Oshawott was still very embarrassed. He wondered how long Emolga wanted to do this, it couldn't be much longer, could it? He had gotten his point across, and even though Oshawott's face was a deep scarlet at this point, he was now doing something far beyond his worst nightmares, /and he was somehow surviving/.

"Well! Let's get ready for our trip!" Emolga said with a grin, as if nothing was out of the ordinary. His excited expression continued without attention to the audible crinkling noise that emanated from his waist as he turned between the other two Pokemon in this now-crinkly trio. Did he mean that the rest of their trip preparations were going to happen dressed like this?? Oshawott rotated to face Snivy in a panic, hoping she would say something to rescue him from this fate.

"No" Snivy said, simply. Oshawott felt a torrent of relief at this single syllable. She was the voice of reason as always! If Snivy wasn't on board with this idea, the battle was won. He figured that his discomfort would soon end, and they could get along with their largely diaper-free lives. "There's no more preparations that need to be done" Snivy continued. Oshawott relaxed a little as Snivy continued her reasoned response. "We should probably eat first, and then we can be on our way!"

Coming to think of it, Oshawott was getting a little hungry. "Yeah! That's a good idea!" He hadn't noticed because of all the excitement, but he actually hadn't eaten anything today. He started to undo the tapes of his diaper. This was sure an enlightening experiment, but he was thoroughly glad to be over with it, and food seemed like a great way to get his mind off of today's horrors.

"Hmm?" Snivy eyed Oshawott. "What do you think you're doing?" she vocalized, observing Oshawott pulling the tape from the front of his diaper. This question caught Oshawott by surprise, he was just getting ready to go eat a meal with them. Surely they weren't planning on staying in *these* for that, were they? Snivy and Emolga's expressions told him all he needed to know. "O-oh no." Oshawott stammered.

* Saved Seats
It didn't take long to find a place to eat, though Oshawott took no place in the decision-making process. His mind stubbornly avoided the topic in favor of the far-more compelling topic of the many reactions he was drawing with his new image. Every time a new Pokemon noticed his poofy underwear, his face ignited anew into a deep scarlet.

Oshawott rehearsed excuses for nobody in particular to justify why he was dressed like a large toddler in the middle of the square--hoping that any preparation could help him avert some of the embarrassment that would undoubtedly surface if he had to interact with anyone.

He didn't need to wait long to test his efforts, because a Pokemon did eventually walk up and ask why they were wearing diapers. It became apparent that no amount of preparation was enough to prepare Oshawott for this. He let Emolga do the talking because there was absolutely no way he was ready to interact with /anyone/ like this.

The fact that Oshawott was drawing attention at all was enough that his face was contorting from one uncomfortable expression to the next with each passing glance. Despite Emolga's insistence he suspected there was just /no way/ his two friends were dealing with this.

Fueled by this suspicion, Oshawott peered at Emolga. He appeared to not have a care in the world. Oshawott envied his nerve. Did this really not embarrass him even a little? He then spied Snivy, who Oshawott noticed was starting to blush a little too. It was plainly visible, but it was also evident that this didn't affect her nearly as badly as it did Oshawott. Oshawott felt for her, what had he gotten them into?

As they entered the cafe, Oshawott took in his surroundings. This cafe was a large circular building with a bar in the middle. The floor was sloped to the bar as if to entice its patrons to it's

Emolga crinkled to the center of the room where the circular bar stood out from a sea of tables. He was ready to order, and even though his crinkly choice of underwear was in full view of the entire cafe, he did so without hesitation. Oshawott gaped at him, he knew Emolga was brave, but he was on another level! He stood there for a few moments admiring Emolga's grit until it occurred to him, wait, *he had to do it too!*

Oshawott hadn't even made any movements towards the bar, but the anticipation flustered him completely. How could he just walk up there and order with his crinkly rump on display as if nothing was wrong?? The world around him spun as the thought of having the entire cafe as his audience swirled through his mind. As Oshawott stood there listless, he felt a vine behind him tap him on his shoulder. Oshawott spun around to look for their source and saw Snivy, who was gazing at him with a subtle, but encouraging smile. This did make Oshawott feel a little better, but he was still extraordinarily self-conscious.

In the square, everyone was on the move and had things they were focusing on. However in this packed cafe, everyone had a clear view of the bar, and his audience was captive for as long as their beverages remained topped off. He wouldn't just have his diapered derriere on display in passing, *everyone* would have as much time as they needed to inspect it as thoroughly as they wanted while he was up there.

It was his turn to go up.

Trying his hardest to steel his nerves, he moved one foot ahead of the other, and then froze. Had he done it? Had he already gathered the attention of the patrons? Oshawott didn't know, and he didn't want to check. He stood there, willing his other foot to step forwards as well, but it refused to budge. His nerves were at their limit.

*THWACK*

Oshawott felt a sharp rap on his padded butt that pushed him forward with enough force to lift his other foot off the ground and ahead of them. It didn't really hurt, but it was much louder than he was comfortable with. His embarrassment was insurmountable now; everyone was surely watching him after that noise, but he had momentum! He just had to keep moving! Left foot, right foot, left foot, right foot. Oshawott feared that if he stopped, he would freeze up again.

And finally, after what felt like an hour he made it! Oshawott made it to the bar! The Panpour behind the bar gaped at him incredulously, this entire display had looked as strange as he had feared it had. They stood there, staring at each other for a few seconds, Oshawott's complexion resembling that of a tomato more with each passing moment until Panpour finally snapped out of his stupor. He evidently didn't know how to react to the display that just occurred in front of him, but he tried his best to mask his discombobulation anyway.

"What can I get for you?" Panpour queried, a slightly stupefied expression still plastered across his face. Oshawott forgot to decide what he wanted to order, and he was in no state to do so now. He couldn't just stand there, not after all of the effort it took to get there, so Oshawott opened his mouth and prayed that what came out would be comprehensible. "I-I... I'll have the b-berry, uh..." he stammered "...the smoothie, with the berries that, uh..." Oshawott was losing it. All eyes were on him, and he felt the pressure of every last one weigh on him.

"He'll have a Pecha Berry smoothie" said a calm voice behind him, he swung around to see Snivy confidently ambling towards the bar. He was saved! "...and I'll have a Calcium Carbos Stew, those are delicious!" she continued. "Y-yeah, that sounds good." Oshawott stuttered as his savior proceeded past him, her diaper audibly crinkling with each nonchalant step towards the bar. She held out a handful of Poke to the bartender who gladly accepted her payment.

Oshawott caught a glimpse of the Pokemon behind them, and several of them were indeed staring at him. His face ignited in an even more maroon shame, something he thought not possible after the previous 30 seconds. Oshawott really couldn't blame them, he had undoubtedly put on quite a show.

Among the faces of the Pokemon, he noticed Emolga with a grin on his face as he waved furiously, trying to capture their attention. "I saved you seats!" he hollered. Oshawott didn't get it. Why didn't anyone pay attention to him? He was up here moments ago in his diapers too.

When Snivy and Oshawott got their food and sat down with Emolga, Oshawott was obsessing over the events of the visit to this cafe so far in excruciating detail. The other Pokemon had all gone back to their conversations and drinks, but Oshawott couldn't help but let the memory of the event steep in his mind. "Sorry about the boost" Snivy interrupted. "It looked like you were stuck and it looked like that might have been all you needed to get going." Oshawott frowned. "It's okay" he said truthfully. He wasn't angry, and it actually had helped him along. If only he hadn't fumbled his words at the last minute.

The two of them joined Emolga at the table with their orders. Oshawott collapsed onto the chair as his bottom bounced slightly on its surface. He noticed that these chairs were more comfortable than he remembered this kind being. He guessed that there were some perks to wearing these garments of shame.

It looked like Emolga was waiting for this moment, because the second they both sat down, he catapulted into conversation about how they were going to get to their destination.
